name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to destroy'
        required: true
        type: choice
        options:
          - prod
          - uat
      confirmation:
        description: 'Type "DESTROY" to confirm deletion'
        required: true
        type: string

permissions:
  contents: read

jobs:
  destroy-infrastructure:
    name: Destroy - ${{ github.event.inputs.environment }}
    if: github.event.inputs.confirmation == 'DESTROY'
    uses: ./.github/workflows/deploy.yml
    with:
      name: "hub-${{ github.event.inputs.environment }}-destroy"
      environment: "${{ github.event.inputs.environment }}"
      terraform_folder: hub/${{ github.event.inputs.environment }}
      apply: true
      terraform_destroy: true
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
